apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-reader
  namespace: formazione-sou
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view  # usa il ruolo predefinito "view"
subjects:
  - kind: ServiceAccount
    name: cluster-reader
    namespace: formazione-sou


