apiVersion: v1
kind: Secret
metadata:
  name: cluster-reader-token
  namespace: formazione-sou
  annotations:
    kubernetes.io/service-account.name: cluster-reader
type: kubernetes.io/service-account-token

